site_name: TGPy Guide
theme:
  name: material
  features:
    - navigation.instant
plugins:
  - search
markdown_extensions:
  - toc:
      permalink: true
nav:
  - index.md
  - installation.md
  - basics.md
  - variables.md
  - code_detection.md