site_name: TGPy Guide
repo_url: https://github.com/tm-a-t/TGPy
repo_name: tm-a-t/TGPy
edit_uri: edit/master/guide/docs/
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
plugins:
  - search
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tilde
nav:
  - Home: index.md
  - installation.md
  - basics.md
  - builtins.md
  - code_detection.md
  - Advanced:
    - hooks.md
    - context.md
