name: Build & deploy guide

on:
  push:
    paths:
      - 'guide/**'

jobs:
  deploy:
    name: Build & deploy guide
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    defaults:
      run:
        working-directory: guide

    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          apt update -y
          apt install -y openssh-client rsync
      - name: Build
        run: mkdocs build
      - name: Setup ssh
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          eval $(ssh-agent -s)
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          ssh-add <(echo $PRIVATE_KEY | base64 -d)
      - name: Deploy
        env:
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
        run: rsync -rlt --delete ./site/ $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH/

